# Generated by Django 5.2.8 on 2025-12-06 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="users.organizer",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participating_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="venues.venue",
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["slug"], name="events_even_slug_f63252_idx"),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["start_datetime"], name="events_even_start_d_071e49_idx"
            ),
        ),
    ]
