# Generated by Django 5.2.8 on 2025-12-08 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(default="iTicket", max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("phone_2", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "support_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("work_hours", models.CharField(blank=True, max_length=255, null=True)),
                ("telegram", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
                ("terms_url", models.URLField(blank=True, null=True)),
                ("privacy_policy_url", models.URLField(blank=True, null=True)),
                ("google_map", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Information",
            },
        ),
    ]
