# Generated by Django 5.2.8 on 2025-12-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
